// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
/// pUSD events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(string, tag="1")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Wrapped {
    #[prost(string, tag="1")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unwrapped {
    #[prost(string, tag="1")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// Adapter events (shared)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionSplit {
    #[prost(string, tag="1")]
    pub initiator: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsMerged {
    #[prost(string, tag="1")]
    pub initiator: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsRedeemed {
    #[prost(string, tag="1")]
    pub initiator: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag="3")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub payout: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// NegRisk-specific
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsConverted {
    #[prost(string, tag="1")]
    pub initiator: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub index_set: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub amount_out: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// Container messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PusdEvents {
    #[prost(message, repeated, tag="1")]
    pub transfer: ::prost::alloc::vec::Vec<Transfer>,
    #[prost(message, repeated, tag="2")]
    pub wrapped: ::prost::alloc::vec::Vec<Wrapped>,
    #[prost(message, repeated, tag="3")]
    pub unwrapped: ::prost::alloc::vec::Vec<Unwrapped>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfAdapterEvents {
    #[prost(message, repeated, tag="1")]
    pub position_split: ::prost::alloc::vec::Vec<PositionSplit>,
    #[prost(message, repeated, tag="2")]
    pub positions_merged: ::prost::alloc::vec::Vec<PositionsMerged>,
    #[prost(message, repeated, tag="3")]
    pub positions_redeemed: ::prost::alloc::vec::Vec<PositionsRedeemed>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskCtfAdapterEvents {
    #[prost(message, repeated, tag="1")]
    pub position_split: ::prost::alloc::vec::Vec<PositionSplit>,
    #[prost(message, repeated, tag="2")]
    pub positions_merged: ::prost::alloc::vec::Vec<PositionsMerged>,
    #[prost(message, repeated, tag="3")]
    pub positions_redeemed: ::prost::alloc::vec::Vec<PositionsRedeemed>,
    #[prost(message, repeated, tag="4")]
    pub positions_converted: ::prost::alloc::vec::Vec<PositionsConverted>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllEvents {
    #[prost(message, optional, tag="1")]
    pub pusd_events: ::core::option::Option<PusdEvents>,
    #[prost(message, optional, tag="2")]
    pub ctf_adapter_events: ::core::option::Option<CtfAdapterEvents>,
    #[prost(message, optional, tag="3")]
    pub neg_risk_ctf_adapter_events: ::core::option::Option<NegRiskCtfAdapterEvents>,
}
// @@protoc_insertion_point(module)
