// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketPrepared {
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub oracle: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub fee_bips: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionPrepared {
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub index: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutcomeReported {
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="3")]
    pub outcome: bool,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionSplit {
    #[prost(string, tag="1")]
    pub stakeholder: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsMerge {
    #[prost(string, tag="1")]
    pub stakeholder: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsConverted {
    #[prost(string, tag="1")]
    pub stakeholder: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub index_set: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutRedemption {
    #[prost(string, tag="1")]
    pub redeemer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag="3")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub payout: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewAdmin {
    #[prost(string, tag="1")]
    pub new_admin_address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub admin: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovedAdmin {
    #[prost(string, tag="1")]
    pub removed_admin: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub admin: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketEvents {
    #[prost(message, repeated, tag="1")]
    pub market_prepared: ::prost::alloc::vec::Vec<MarketPrepared>,
    #[prost(message, repeated, tag="2")]
    pub question_prepared: ::prost::alloc::vec::Vec<QuestionPrepared>,
    #[prost(message, repeated, tag="3")]
    pub outcome_reported: ::prost::alloc::vec::Vec<OutcomeReported>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingEvents {
    #[prost(message, repeated, tag="1")]
    pub position_split: ::prost::alloc::vec::Vec<PositionSplit>,
    #[prost(message, repeated, tag="2")]
    pub positions_merge: ::prost::alloc::vec::Vec<PositionsMerge>,
    #[prost(message, repeated, tag="3")]
    pub positions_converted: ::prost::alloc::vec::Vec<PositionsConverted>,
    #[prost(message, repeated, tag="4")]
    pub payout_redemption: ::prost::alloc::vec::Vec<PayoutRedemption>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdminEvents {
    #[prost(message, repeated, tag="1")]
    pub new_admin: ::prost::alloc::vec::Vec<NewAdmin>,
    #[prost(message, repeated, tag="2")]
    pub removed_admin: ::prost::alloc::vec::Vec<RemovedAdmin>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllEvents {
    #[prost(message, optional, tag="1")]
    pub market_events: ::core::option::Option<MarketEvents>,
    #[prost(message, optional, tag="2")]
    pub trading_events: ::core::option::Option<TradingEvents>,
    #[prost(message, optional, tag="3")]
    pub admin_events: ::core::option::Option<AdminEvents>,
}
// @@protoc_insertion_point(module)
