// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
// --- OptimisticOracleV2 events (primary — 222k+ txns) ---

/// ProposePrice - emitted when someone proposes a resolution on V2
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposePrice {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub proposed_price: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub expiration_timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub currency: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// DisputePrice - emitted when someone disputes a proposed price on V2
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputePrice {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub proposed_price: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// Settle - emitted when a V2 request reaches final settlement
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleV2 {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub payout: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OracleV2Events {
    #[prost(message, repeated, tag="1")]
    pub propose_price: ::prost::alloc::vec::Vec<ProposePrice>,
    #[prost(message, repeated, tag="2")]
    pub dispute_price: ::prost::alloc::vec::Vec<DisputePrice>,
    #[prost(message, repeated, tag="3")]
    pub settle: ::prost::alloc::vec::Vec<SettleV2>,
}
// --- OptimisticOracleV3 events (secondary — 47 txns) ---

/// AssertionMade - emitted when a resolution is proposed to the V3 oracle
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionMade {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub domain_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub claim: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub asserter: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub callback_recipient: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub escalation_manager: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub caller: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub expiration_time: u64,
    #[prost(string, tag="9")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub bond: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="11")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="12")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// AssertionDisputed - emitted when someone disputes a pending V3 assertion
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionDisputed {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// AssertionSettled - emitted when a V3 assertion reaches final settlement
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionSettled {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub bond_recipient: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub disputed: bool,
    #[prost(bool, tag="4")]
    pub settlement_resolution: bool,
    #[prost(string, tag="5")]
    pub settle_caller: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OracleV3Events {
    #[prost(message, repeated, tag="1")]
    pub assertion_made: ::prost::alloc::vec::Vec<AssertionMade>,
    #[prost(message, repeated, tag="2")]
    pub assertion_disputed: ::prost::alloc::vec::Vec<AssertionDisputed>,
    #[prost(message, repeated, tag="3")]
    pub assertion_settled: ::prost::alloc::vec::Vec<AssertionSettled>,
}
// --- Unified dispute alerts (from both V2 and V3) ---

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputeAlert {
    #[prost(string, tag="1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="6")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputeAlerts {
    #[prost(message, repeated, tag="1")]
    pub alerts: ::prost::alloc::vec::Vec<DisputeAlert>,
}
/// AllEvents wraps all event types
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllEvents {
    #[prost(message, optional, tag="1")]
    pub v2_events: ::core::option::Option<OracleV2Events>,
    #[prost(message, optional, tag="2")]
    pub v3_events: ::core::option::Option<OracleV3Events>,
    #[prost(message, optional, tag="3")]
    pub dispute_alerts: ::core::option::Option<DisputeAlerts>,
}
// @@protoc_insertion_point(module)
