// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
// === OptimisticOracleV2 events ===

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposePrice {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub proposed_price: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub expiration_timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub currency: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputePrice {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub proposed_price: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleV2 {
    #[prost(string, tag="1")]
    pub requester: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub payout: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OracleV2Events {
    #[prost(message, repeated, tag="1")]
    pub propose_price: ::prost::alloc::vec::Vec<ProposePrice>,
    #[prost(message, repeated, tag="2")]
    pub dispute_price: ::prost::alloc::vec::Vec<DisputePrice>,
    #[prost(message, repeated, tag="3")]
    pub settle: ::prost::alloc::vec::Vec<SettleV2>,
}
// === OptimisticOracleV3 events ===

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionMade {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub domain_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub claim: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub asserter: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub callback_recipient: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub escalation_manager: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub caller: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub expiration_time: u64,
    #[prost(string, tag="9")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub bond: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="11")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="12")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionDisputed {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssertionSettled {
    #[prost(bytes="vec", tag="1")]
    pub assertion_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub bond_recipient: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub disputed: bool,
    #[prost(bool, tag="4")]
    pub settlement_resolution: bool,
    #[prost(string, tag="5")]
    pub settle_caller: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OracleV3Events {
    #[prost(message, repeated, tag="1")]
    pub assertion_made: ::prost::alloc::vec::Vec<AssertionMade>,
    #[prost(message, repeated, tag="2")]
    pub assertion_disputed: ::prost::alloc::vec::Vec<AssertionDisputed>,
    #[prost(message, repeated, tag="3")]
    pub assertion_settled: ::prost::alloc::vec::Vec<AssertionSettled>,
}
// === CTF Adapter events (question lifecycle) ===

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionInitialized {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub request_timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub creator: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub reward_token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub reward: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub proposal_bond: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionResolved {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub settled_price: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub payouts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionEmergencyResolved {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag="2")]
    pub payouts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionFlagged {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionUnflagged {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionPaused {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionUnpaused {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionReset {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AncillaryDataUpdated {
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub update_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdapterAdmin {
    #[prost(string, tag="1")]
    pub admin: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub target_admin: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_addition: bool,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdapterEvents {
    #[prost(message, repeated, tag="1")]
    pub question_initialized: ::prost::alloc::vec::Vec<QuestionInitialized>,
    #[prost(message, repeated, tag="2")]
    pub question_resolved: ::prost::alloc::vec::Vec<QuestionResolved>,
    #[prost(message, repeated, tag="3")]
    pub question_emergency_resolved: ::prost::alloc::vec::Vec<QuestionEmergencyResolved>,
    #[prost(message, repeated, tag="4")]
    pub question_flagged: ::prost::alloc::vec::Vec<QuestionFlagged>,
    #[prost(message, repeated, tag="5")]
    pub question_unflagged: ::prost::alloc::vec::Vec<QuestionUnflagged>,
    #[prost(message, repeated, tag="6")]
    pub question_paused: ::prost::alloc::vec::Vec<QuestionPaused>,
    #[prost(message, repeated, tag="7")]
    pub question_unpaused: ::prost::alloc::vec::Vec<QuestionUnpaused>,
    #[prost(message, repeated, tag="8")]
    pub question_reset: ::prost::alloc::vec::Vec<QuestionReset>,
    #[prost(message, repeated, tag="9")]
    pub ancillary_data_updated: ::prost::alloc::vec::Vec<AncillaryDataUpdated>,
    #[prost(message, repeated, tag="10")]
    pub admin_changes: ::prost::alloc::vec::Vec<AdapterAdmin>,
}
// === Enhanced unified types ===

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputeAlert {
    #[prost(string, tag="1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub alert_type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub identifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub disputer: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag="6")]
    pub payouts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="7")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisputeAlerts {
    #[prost(message, repeated, tag="1")]
    pub alerts: ::prost::alloc::vec::Vec<DisputeAlert>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResolutionEvents {
    #[prost(message, optional, tag="1")]
    pub oracle_v2: ::core::option::Option<OracleV2Events>,
    #[prost(message, optional, tag="2")]
    pub oracle_v3: ::core::option::Option<OracleV3Events>,
    #[prost(message, optional, tag="3")]
    pub adapter: ::core::option::Option<AdapterEvents>,
    #[prost(message, optional, tag="4")]
    pub dispute_alerts: ::core::option::Option<DisputeAlerts>,
}
// @@protoc_insertion_point(module)
