// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalletDeployed {
    #[prost(string, tag="1")]
    pub wallet: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub implementation: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImplementationAuthorized {
    #[prost(string, tag="1")]
    pub implementation: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FactoryEvents {
    #[prost(message, repeated, tag="1")]
    pub wallet_deployed: ::prost::alloc::vec::Vec<WalletDeployed>,
    #[prost(message, repeated, tag="2")]
    pub implementation_authorized: ::prost::alloc::vec::Vec<ImplementationAuthorized>,
}
// @@protoc_insertion_point(module)
