// @generated
// This file is @generated by prost-build.
/// TransactionContext contains metadata about the transaction and log entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionContext {
    #[prost(string, tag="1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub log_index: u64,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(uint64, tag="4")]
    pub timestamp: u64,
}
/// OrderFilled - emitted when an order is filled (main trading event)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderFilled {
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub taker: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub maker_asset_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub taker_asset_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub taker_amount_filled: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// OrderCancelled - emitted when an order is cancelled
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderCancelled {
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// OrdersMatched - emitted when a taker order is matched against maker orders
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrdersMatched {
    #[prost(bytes="vec", tag="1")]
    pub taker_order_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub taker_order_maker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub maker_asset_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub taker_asset_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub taker_amount_filled: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// TokenRegistered - emitted when a token pair is registered for trading
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRegistered {
    #[prost(string, tag="1")]
    pub token0: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token1: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// FeeCharged - emitted when protocol fees are collected
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeCharged {
    #[prost(string, tag="1")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub tx: ::core::option::Option<TransactionContext>,
}
/// ExchangeEvents is a collection of all exchange trading events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeEvents {
    #[prost(message, repeated, tag="1")]
    pub order_filled: ::prost::alloc::vec::Vec<OrderFilled>,
    #[prost(message, repeated, tag="2")]
    pub order_cancelled: ::prost::alloc::vec::Vec<OrderCancelled>,
    #[prost(message, repeated, tag="3")]
    pub orders_matched: ::prost::alloc::vec::Vec<OrdersMatched>,
}
/// RegistryEvents is a collection of all token registry events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistryEvents {
    #[prost(message, repeated, tag="1")]
    pub token_registered: ::prost::alloc::vec::Vec<TokenRegistered>,
}
/// FeeEvents is a collection of all fee collection events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeEvents {
    #[prost(message, repeated, tag="1")]
    pub fee_charged: ::prost::alloc::vec::Vec<FeeCharged>,
}
/// AllEvents combines all event types
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllEvents {
    #[prost(message, optional, tag="1")]
    pub exchange_events: ::core::option::Option<ExchangeEvents>,
    #[prost(message, optional, tag="2")]
    pub registry_events: ::core::option::Option<RegistryEvents>,
    #[prost(message, optional, tag="3")]
    pub fee_events: ::core::option::Option<FeeEvents>,
}
// @@protoc_insertion_point(module)
